# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Let's fly
tagline:          
description:      Collection of my scribbles
url:              http://myggum.github.io
disqus_shortname: myggumongithub


author:
  name:           myggum
  url:
  picture: 

pages_list:       
    About: '/about'
    Archive: '/archive'
    Tags: '/tags'
    Feed: '/atom.xml'
    # C.V.: '/cv'
    # Research: '/research'



# paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
